// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/api.proto

package go_micro_api_platform

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_Create EventType = 0
	EventType_Delete EventType = 1
	EventType_Update EventType = 2
)

var EventType_name = map[int32]string{
	0: "Create",
	1: "Delete",
	2: "Update",
}

var EventType_value = map[string]int32{
	"Create": 0,
	"Delete": 1,
	"Update": 2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{0}
}

type CreateServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceRequest) Reset()         { *m = CreateServiceRequest{} }
func (m *CreateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServiceRequest) ProtoMessage()    {}
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{0}
}

func (m *CreateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceRequest.Unmarshal(m, b)
}
func (m *CreateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceRequest.Marshal(b, m, deterministic)
}
func (m *CreateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceRequest.Merge(m, src)
}
func (m *CreateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServiceRequest.Size(m)
}
func (m *CreateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceRequest proto.InternalMessageInfo

func (m *CreateServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type CreateServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServiceResponse) Reset()         { *m = CreateServiceResponse{} }
func (m *CreateServiceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateServiceResponse) ProtoMessage()    {}
func (*CreateServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{1}
}

func (m *CreateServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServiceResponse.Unmarshal(m, b)
}
func (m *CreateServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServiceResponse.Marshal(b, m, deterministic)
}
func (m *CreateServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServiceResponse.Merge(m, src)
}
func (m *CreateServiceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateServiceResponse.Size(m)
}
func (m *CreateServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServiceResponse proto.InternalMessageInfo

type ReadServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadServiceRequest) Reset()         { *m = ReadServiceRequest{} }
func (m *ReadServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ReadServiceRequest) ProtoMessage()    {}
func (*ReadServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{2}
}

func (m *ReadServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadServiceRequest.Unmarshal(m, b)
}
func (m *ReadServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadServiceRequest.Marshal(b, m, deterministic)
}
func (m *ReadServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadServiceRequest.Merge(m, src)
}
func (m *ReadServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ReadServiceRequest.Size(m)
}
func (m *ReadServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadServiceRequest proto.InternalMessageInfo

func (m *ReadServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type ReadServiceResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadServiceResponse) Reset()         { *m = ReadServiceResponse{} }
func (m *ReadServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ReadServiceResponse) ProtoMessage()    {}
func (*ReadServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{3}
}

func (m *ReadServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadServiceResponse.Unmarshal(m, b)
}
func (m *ReadServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadServiceResponse.Marshal(b, m, deterministic)
}
func (m *ReadServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadServiceResponse.Merge(m, src)
}
func (m *ReadServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ReadServiceResponse.Size(m)
}
func (m *ReadServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadServiceResponse proto.InternalMessageInfo

func (m *ReadServiceResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type UpdateServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServiceRequest) Reset()         { *m = UpdateServiceRequest{} }
func (m *UpdateServiceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateServiceRequest) ProtoMessage()    {}
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{4}
}

func (m *UpdateServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServiceRequest.Unmarshal(m, b)
}
func (m *UpdateServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServiceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServiceRequest.Merge(m, src)
}
func (m *UpdateServiceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateServiceRequest.Size(m)
}
func (m *UpdateServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServiceRequest proto.InternalMessageInfo

func (m *UpdateServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type UpdateServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateServiceResponse) Reset()         { *m = UpdateServiceResponse{} }
func (m *UpdateServiceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateServiceResponse) ProtoMessage()    {}
func (*UpdateServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{5}
}

func (m *UpdateServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateServiceResponse.Unmarshal(m, b)
}
func (m *UpdateServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateServiceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateServiceResponse.Merge(m, src)
}
func (m *UpdateServiceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateServiceResponse.Size(m)
}
func (m *UpdateServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateServiceResponse proto.InternalMessageInfo

type DeleteServiceRequest struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteServiceRequest) Reset()         { *m = DeleteServiceRequest{} }
func (m *DeleteServiceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteServiceRequest) ProtoMessage()    {}
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{6}
}

func (m *DeleteServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteServiceRequest.Unmarshal(m, b)
}
func (m *DeleteServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteServiceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteServiceRequest.Merge(m, src)
}
func (m *DeleteServiceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteServiceRequest.Size(m)
}
func (m *DeleteServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteServiceRequest proto.InternalMessageInfo

func (m *DeleteServiceRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type DeleteServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteServiceResponse) Reset()         { *m = DeleteServiceResponse{} }
func (m *DeleteServiceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteServiceResponse) ProtoMessage()    {}
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{7}
}

func (m *DeleteServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteServiceResponse.Unmarshal(m, b)
}
func (m *DeleteServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteServiceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteServiceResponse.Merge(m, src)
}
func (m *DeleteServiceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteServiceResponse.Size(m)
}
func (m *DeleteServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteServiceResponse proto.InternalMessageInfo

type ListServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesRequest) Reset()         { *m = ListServicesRequest{} }
func (m *ListServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListServicesRequest) ProtoMessage()    {}
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{8}
}

func (m *ListServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesRequest.Unmarshal(m, b)
}
func (m *ListServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesRequest.Marshal(b, m, deterministic)
}
func (m *ListServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesRequest.Merge(m, src)
}
func (m *ListServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListServicesRequest.Size(m)
}
func (m *ListServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesRequest proto.InternalMessageInfo

type ListServicesResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListServicesResponse) Reset()         { *m = ListServicesResponse{} }
func (m *ListServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListServicesResponse) ProtoMessage()    {}
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{9}
}

func (m *ListServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesResponse.Unmarshal(m, b)
}
func (m *ListServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesResponse.Marshal(b, m, deterministic)
}
func (m *ListServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesResponse.Merge(m, src)
}
func (m *ListServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListServicesResponse.Size(m)
}
func (m *ListServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesResponse proto.InternalMessageInfo

func (m *ListServicesResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Source               string            `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Type                 string            `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{10}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Event struct {
	Type                 EventType `protobuf:"varint,1,opt,name=type,proto3,enum=go.micro.api.platform.EventType" json:"type,omitempty"`
	Service              *Service  `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2df576b66d12087a, []int{11}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_Create
}

func (m *Event) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func init() {
	proto.RegisterEnum("go.micro.api.platform.EventType", EventType_name, EventType_value)
	proto.RegisterType((*CreateServiceRequest)(nil), "go.micro.api.platform.CreateServiceRequest")
	proto.RegisterType((*CreateServiceResponse)(nil), "go.micro.api.platform.CreateServiceResponse")
	proto.RegisterType((*ReadServiceRequest)(nil), "go.micro.api.platform.ReadServiceRequest")
	proto.RegisterType((*ReadServiceResponse)(nil), "go.micro.api.platform.ReadServiceResponse")
	proto.RegisterType((*UpdateServiceRequest)(nil), "go.micro.api.platform.UpdateServiceRequest")
	proto.RegisterType((*UpdateServiceResponse)(nil), "go.micro.api.platform.UpdateServiceResponse")
	proto.RegisterType((*DeleteServiceRequest)(nil), "go.micro.api.platform.DeleteServiceRequest")
	proto.RegisterType((*DeleteServiceResponse)(nil), "go.micro.api.platform.DeleteServiceResponse")
	proto.RegisterType((*ListServicesRequest)(nil), "go.micro.api.platform.ListServicesRequest")
	proto.RegisterType((*ListServicesResponse)(nil), "go.micro.api.platform.ListServicesResponse")
	proto.RegisterType((*Service)(nil), "go.micro.api.platform.Service")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.api.platform.Service.MetadataEntry")
	proto.RegisterType((*Event)(nil), "go.micro.api.platform.Event")
}

func init() { proto.RegisterFile("api/proto/api.proto", fileDescriptor_2df576b66d12087a) }

var fileDescriptor_2df576b66d12087a = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x6e, 0xfa, 0xbf, 0xb3, 0x14, 0x55, 0xd3, 0x16, 0xa2, 0x1e, 0x50, 0x95, 0x13, 0xec, 0xae,
	0x52, 0xa9, 0x70, 0x58, 0x2d, 0x47, 0x58, 0x89, 0x03, 0xa0, 0x12, 0xe0, 0x01, 0x4c, 0x3b, 0x45,
	0x11, 0x69, 0x1c, 0x6c, 0xb7, 0xa8, 0x4f, 0xc4, 0xbb, 0xf1, 0x14, 0x28, 0xb6, 0x5b, 0x35, 0x25,
	0x46, 0x5d, 0x29, 0xb7, 0xf1, 0xe4, 0x9b, 0xef, 0x9b, 0x99, 0xf8, 0x4b, 0x60, 0xc0, 0xb2, 0x78,
	0x9a, 0x09, 0xae, 0xf8, 0x94, 0x65, 0x71, 0xa8, 0x23, 0x1c, 0x7d, 0xe7, 0xe1, 0x3a, 0x5e, 0x08,
	0x1e, 0xea, 0x5c, 0xc2, 0xd4, 0x8a, 0x8b, 0x75, 0x30, 0x87, 0xe1, 0x1b, 0x41, 0x4c, 0xd1, 0x67,
	0x12, 0xdb, 0x78, 0x41, 0x11, 0xfd, 0xdc, 0x90, 0x54, 0x78, 0x0b, 0x1d, 0x69, 0x32, 0xbe, 0x37,
	0xf1, 0x9e, 0x5f, 0xce, 0x9e, 0x85, 0xa5, 0x04, 0xe1, 0xbe, 0x6e, 0x0f, 0x0f, 0x9e, 0xc2, 0xe8,
	0x84, 0x51, 0x66, 0x3c, 0x95, 0x14, 0x7c, 0x04, 0x8c, 0x88, 0x2d, 0x2b, 0x13, 0xfa, 0x04, 0x83,
	0x02, 0x9f, 0x91, 0xc1, 0x3b, 0xe8, 0x5a, 0x84, 0xf4, 0xbd, 0x49, 0xe3, 0x0c, 0xc6, 0x03, 0x3e,
	0xdf, 0xc6, 0xd7, 0x6c, 0x59, 0xf1, 0x36, 0x4e, 0x18, 0xed, 0x36, 0xe6, 0x30, 0x7c, 0x4b, 0x09,
	0x55, 0x2b, 0x75, 0xc2, 0x68, 0xa5, 0x46, 0x30, 0x78, 0x1f, 0x4b, 0x65, 0xd3, 0xd2, 0x2a, 0x05,
	0x11, 0x0c, 0x8b, 0xe9, 0x0a, 0x16, 0xf8, 0xc7, 0x83, 0x8e, 0xcd, 0x22, 0x42, 0x33, 0x65, 0x6b,
	0x33, 0xc6, 0x45, 0xa4, 0x63, 0xf4, 0xa1, 0xb3, 0x25, 0x21, 0x63, 0x9e, 0xfa, 0x75, 0x9d, 0xde,
	0x1f, 0xf1, 0x09, 0xb4, 0x25, 0xdf, 0x88, 0x05, 0xf9, 0x0d, 0xfd, 0xc0, 0x9e, 0x72, 0x16, 0xb5,
	0xcb, 0xc8, 0x6f, 0x1a, 0x96, 0x3c, 0xc6, 0x77, 0xd0, 0x5d, 0x93, 0x62, 0x4b, 0xa6, 0x98, 0xdf,
	0xd2, 0x1d, 0xde, 0xfc, 0xbf, 0xc3, 0xf0, 0x83, 0x85, 0xdf, 0xa7, 0x4a, 0xec, 0xa2, 0x43, 0xf5,
	0xf8, 0x35, 0xf4, 0x0a, 0x8f, 0xb0, 0x0f, 0x8d, 0x1f, 0xb4, 0xb3, 0x3d, 0xe7, 0x21, 0x0e, 0xa1,
	0xb5, 0x65, 0xc9, 0x86, 0x6c, 0xc3, 0xe6, 0x70, 0x57, 0xbf, 0xf5, 0x82, 0x5f, 0xd0, 0xba, 0xdf,
	0x52, 0xaa, 0xf0, 0x95, 0xed, 0x31, 0xaf, 0x7a, 0x3c, 0x9b, 0x38, 0x7a, 0xd1, 0xd8, 0x2f, 0xbb,
	0x8c, 0xec, 0x14, 0x47, 0x6f, 0xba, 0xfe, 0xa0, 0x37, 0x7d, 0x35, 0x85, 0x8b, 0x03, 0x19, 0x02,
	0xb4, 0x8d, 0xdf, 0xfa, 0xb5, 0x3c, 0x36, 0x57, 0xa0, 0xef, 0xe5, 0xb1, 0xb9, 0x79, 0xfd, 0xfa,
	0xec, 0x77, 0x13, 0xba, 0x73, 0x4b, 0x87, 0x09, 0xf4, 0x0a, 0x06, 0xc5, 0x6b, 0x87, 0x6e, 0xd9,
	0x87, 0x61, 0x7c, 0x73, 0x1e, 0xd8, 0x5e, 0xbd, 0x1a, 0xae, 0xe0, 0xf2, 0xc8, 0xa5, 0xf8, 0xc2,
	0x51, 0xfe, 0xef, 0x97, 0x61, 0x7c, 0x75, 0x0e, 0xf4, 0xa0, 0x93, 0x40, 0xaf, 0x60, 0x34, 0xe7,
	0x54, 0x65, 0x06, 0x77, 0x4e, 0x55, 0xee, 0x5d, 0xad, 0x56, 0xf0, 0x9a, 0x53, 0xad, 0xcc, 0xe3,
	0x4e, 0xb5, 0x72, 0xfb, 0xd6, 0x30, 0x86, 0x47, 0xc7, 0x4e, 0x45, 0xd7, 0x66, 0x4a, 0x5c, 0x3e,
	0xbe, 0x3e, 0x0b, 0xbb, 0x97, 0xfa, 0xd6, 0xd6, 0x7f, 0x8b, 0x97, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x9a, 0x68, 0xfb, 0xd4, 0x44, 0x06, 0x00, 0x00,
}
