name: CI

on:
  push:
    branches-ignore: master

jobs:
  devel_docker_build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         name: Check out repository
       - uses: elgohr/Publish-Docker-Github-Action@2.12
         name: Build and Push Docker Image
         with:
           name: micro/platform
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
