name: CI

on:
  push:
    branches-ignore: master

jobs:
  devel_docker_build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: zenato/docker-action@master
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           repository: micro/services
           tag: ${GITHUB_REF##*/}
